Controllers/AlmacenesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Vereyon.Web;
using WebInventarios.Helpers;
using WebInventarios.Models;
using static WebInventarios.Helpers.ModalHelper;

namespace WebInventarios.Controllers
{
    public class AlmacenesController : Controller
    {
        private readonly ConexionContext _context;
        private readonly IFlashMessage _flashMessage;

        public AlmacenesController(ConexionContext context, IFlashMessage flashMessage)
        {
            _context = context;
            _flashMessage = flashMessage;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Almacenes.ToListAsync());
        }

        [NoDirectAccess]
        public async Task<IActionResult> Crear()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Almacenes model)
        {
            Almacenes almacenes = new()
            {
                //IDAlmacen = model.IDAlmacen,
                DescripcionAlmacen = model.DescripcionAlmacen,
                ReferenciaAlmacen = model.ReferenciaAlmacen,
            };

            try
            {
                _context.Add(almacenes);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("Registro creado.");
                return Json(new
                {
                    isValid = true,
                    html = ModalHelper.RenderRazorViewToString(this, "_ViewAllAlmacenes", _context.Almacenes
                    )
                });

            }
            catch (DbUpdateException dbUpdateException)
            {
                if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                {
                    ModelState.AddModelError(string.Empty, "Ya existe un producto con el mismo nombre.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                }
            }
            catch (Exception exception)
            {
                ModelState.AddModelError(string.Empty, exception.Message);
            }
            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "Create", model) });

        }

        [NoDirectAccess]
        public async Task<IActionResult> Editar(int IDAlmacen)
        {
            Almacenes almacenes = await _context.Almacenes.FindAsync(IDAlmacen);
            if (almacenes == null)
            {
                return NotFound();
            }
            return View(almacenes);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]

        public async Task<IActionResult> Editar(int IDAlmacen,  Almacenes model)
        {
            if(IDAlmacen != model.IDAlmacen)
            {
                return NotFound();
            }

            try
            {
                Almacenes almacenes = await _context.Almacenes.FindAsync(model.IDAlmacen);
                almacenes.DescripcionAlmacen = model.DescripcionAlmacen;
                almacenes.ReferenciaAlmacen = model.ReferenciaAlmacen;
                _context.Update(almacenes);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("Registro actualizado.");
                return Json(new
                {
                    isValid = true,
                    html = ModalHelper.RenderRazorViewToString(this, "_ViewAllAlmacenes", _context.Almacenes)
                });

            }

            catch (DbUpdateException dbUpdateException)
            {
                if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                {
                    ModelState.AddModelError(string.Empty, "Ya existe un producto con el mismo nombre.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                }
            }
            catch (Exception exception)
            {
                ModelState.AddModelError(string.Empty, exception.Message);
            }


            return Json(new
                                {
                                    isValid = true,
                                    html = ModalHelper.RenderRazorViewToString(this, "Editar", _context.Almacenes)
                                });
        }



        [NoDirectAccess]
        public async Task<ActionResult> Delete(int Id)
        {
            Almacenes almacenes = await _context.Almacenes.FindAsync(Id);

            if (almacenes == null)
            {
                return NotFound();
            }
            _context.Remove(almacenes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }

    }
}

Controllers/CuentasController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebInventarios.Controllers
{
    public class CuentasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

    }

}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebInventarios.Models;
using WebInventarios.Helpers;
using static WebInventarios.Helpers.ModalHelper;
using WebInventarios.Comun;
using WebInventarios.Models.ViewModels;

namespace WebInventarios.Controllers
{
    public class ProductosController : Controller
    {
        private readonly ConexionContext _context;
        private readonly IComboshelpers _combos;

        public ProductosController(ConexionContext  context, IComboshelpers combos)
        {
            _context = context;
            _combos = combos;
        }
        // GET: ProductosController
        public async Task <IActionResult> Index()
        {
            return View(await _context.Productos
                .Include(ip => ip.imagenesproducto)
                .ToListAsync());
        }

        // GET: ProductosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductosController/Create
        [NoDirectAccess]
        public async Task<IActionResult> Create()
        {
            CrearProductosViewModel model = new()
            {
                Almacenes = await _combos.GetComboAlmacenes(),

            };
            return View(model);
        }

        // POST: ProductosController/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task  <ActionResult> Create(Producto producto, int IDAlmacen)
        {
            if( producto == null )
            {
                return View("No_es");
            }

            else
            {
                _context.Productos.Add(producto);
                await _context.SaveChangesAsync();

                //  int ProductoID = await _context.Productos.FindAsync(producto.ProductoDesc);

                var Productos = await _context.Productos.Where(p=> p.ProductoDesc == producto.ProductoDesc).FirstOrDefaultAsync();

                if (IDAlmacen > 0)
                {
                    var NEWProductosAlmacen = new ProductosAlmacen
                    {
                        IDAlmacen = IDAlmacen,
                        ProductoId = Productos.ProductoId
                    };

                    _context.ProductosAlmacen.Add(NEWProductosAlmacen);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
          

        }

        // GET: ProductosController/Edit/5
        [NoDirectAccess]
        public async Task <ActionResult> Edit(int ProductoID = 0)
        {
            if (ProductoID > 0)

            {

                IEnumerable<Imagenesproducto> imagenesProductos = await _context.Imagenesproducto.Where(ip => ip.ProductoId == ProductoID).ToListAsync();

                Producto producto = await _context.Productos.FindAsync(ProductoID);
                CrearProductosViewModel model = new()
                {
                    Almacenes = await _combos.GetComboAlmacenes(),
                    ProductoId = producto.ProductoId,
                    ProductoDesc = producto.ProductoDesc,
                    ProductoComentario = producto.ProductoComentario,
                    ProductoCan = producto.ProductoCan,
                    ImagenesProductos = imagenesProductos,
                    
                };
                return View(model);
             }
            
             else
                {
                    return RedirectToAction("Index");
                }
        }

       


        // POST: ProductosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <ActionResult> Edit(int id, EditarProducto producto)
        {

            string? nombreImagen = producto.ImageFile != null ? producto.ImageFile.FileName : null; // Aquí asigna el nombre de la imagen que deseas buscar
           

            Imagenesproducto imagenesproducto = await _context.Imagenesproducto
                .FirstOrDefaultAsync(ip => ip.imagen == nombreImagen);

            if (imagenesproducto == null)
            {
                if (producto.ImageFile != null)
                {
                    SubidasHelper subidasHelper = new SubidasHelper("wwwroot/Imagenes/Productos");
                    string nombreArchivo = await subidasHelper.GuardarArchivoAsync(producto.ImageFile);

                    // Aquí tienes el registro encontrado, puedes trabajar con él
                    var nuevaImagen = new Imagenesproducto
                    {
                        ProductoId = producto.ProductoId,
                        imagen = producto.ImageFile.FileName,
                        NombreArchivo = nombreArchivo,
                    };


                    _context.Imagenesproducto.Add(nuevaImagen);
                    await _context.SaveChangesAsync();

                }

            }
            else if (producto.ImageFile != null)
            {
                //To Do
                // entra aqui luego trabajar esta 
                //var nuevaImagen = new Imagenesproducto
                //{
                //    ProductoId = producto.ProductoId,
                //    imagen = producto.ImageFile.FileName
                //};
                //_context.Imagenesproducto.Add(nuevaImagen);
                //await _context.SaveChangesAsync();

                //SubidasHelper subidasHelper = new SubidasHelper("");
                //string nombreArchivo = await subidasHelper.GuardarArchivoAsync(producto.ImageFile);
            }


            if (producto.IDAlmacen == null)
                {
                    ProductosAlmacen productosAlmacen = await _context.ProductosAlmacen.FindAsync(producto.ProductoId);
                }
            
                Producto product = await _context.Productos.FindAsync(producto.ProductoId);
                product.ProductoDesc = producto.ProductoDesc;
                product.ProductoCan = producto.ProductoCan;
            

                _context.Update(product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            
        }

        // GET: ProductosController/Delete/5
        //[HttpGet]
        //public ActionResult Delete(int id ,int oo)
        //{
        //    return View("Delete");
        //}

        //// POST: ProductosController/Delete/5

        [NoDirectAccess]
        public async Task<ActionResult> Delete(int Id)
        {
            Producto producto =  await _context.Productos.FindAsync(Id);

            if (producto == null)
            {
                return NotFound();
            }
            _context.Remove(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            

        }


            
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebInventarios.Models;
using static WebInventarios.Helpers.ModalHelper;

namespace WebInventarios.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly ConexionContext _context;

        public UsuariosController(ConexionContext context)
        {
            _context = context;
        }
      
        public async Task <IActionResult> Index()
        {
            return View( await _context.Usuarios.ToListAsync());
        }

        // GET: UsuariosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UsuariosController/Create
        [NoDirectAccess]
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsuariosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Create( Usuarios usuarios)
        {
            try
            {
                _context.Usuarios.Add(usuarios);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsuariosController/Edit/5
        public async Task <IActionResult> Edit(int IdUsuarios)
        {
            if (IdUsuarios > 0)
            {
                Usuarios usuarios = await _context.Usuarios.FindAsync(IdUsuarios);
                return View(usuarios);
            }
              else
            {
                return RedirectToAction(nameof(Create));
            }
        }

        // POST: UsuariosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Usuarios usuarios)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(usuarios);

                }
                //if (usuarios == null)
                //{
                //    return View();
                //}
                 _context.Update(usuarios);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsuariosController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: UsuariosController/Delete/5
        
        [NoDirectAccess]
        public async Task <IActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                Usuarios usuarios = await _context.Usuarios.FindAsync(id);

                if (usuarios == null)
                {
                    return NotFound();
                }

                _context.Remove(usuarios);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/No_es.cshtml
<hi> No hay na mi bro </hi>

Views/Shared/_AddorEditDialog.cshtml
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

Views/Shared/_DeleteDialog.cshtml
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-blue-gradient">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estas seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><i style="font-size: 1rem" class="bi bi-exclamation-circle"> </i> No</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete"><i style="font-size: 1rem" class="bi bi-check-circle"> </i> Sí</button>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebInventarios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebInventarios.styles.css" asp-append-version="true" />
       <style>
        header {
            background-image: url("https://localhost:7220/imagenes/noImageProduct.jpg");
            background-size: cover; /* Ajusta la imagen para que cubra todo el fondo */
            background-repeat: no-repeat; /* Evita que la imagen se repita */
            background-position: center center; /* Centra la imagen */
        }
    </style>

</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 container-xxl bd-gutter flex-wrap flex-lg-nowrap" aria-label="Main navigation">
            <div class="container-fluid ">
                <a class="navbar-brand zoom" asp-area="" asp-controller="Home" asp-action="Index">WebInventarios</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    
                    <ul class="navbar-nav flex-row flex-wrap ms-md-auto" >
                        <li class="nav-item zoom">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">
                                <i class="bi bi-person-vcard" title="Usuario">
                                </i>
                            </a>
                        </li>
                        <li class="nav-item zoom">
                            <a  class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">
                                <i class="bi bi-clipboard-check" title="Productos"></i>
                            </a>
                        </li>
                        <li class="nav-item zoom">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Almacenes" asp-action="Index">
                                
                                <i class="bi bi-card-checklist" title="Almacenes">
                                </i>
                            </a>
                        </li>
                        <li class="nav-item zoom">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuentas" asp-action="Index">

                                <i class="bi bi-card-checklist" title="Cerrar Sesion">
                                </i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebInventarios - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>